#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

docker_cpu - Plugin to measure cpu usage of docker containers.

=head1 NOTES

Hopefully this works

=head1 AUTHOR

Contributed by Joe Seegmiller

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

. $MUNIN_LIBDIR/plugins/plugin.sh

DockerCMD=${docker:-$(which docker)}

if [ "$1" = "autoconf" ]; then
  if [ -x $DockerCMD ]; then
    echo yes
    exit 0
  else
    echo no '(docker not found)'
    exit 0
  fi
fi

if [ "$1" = "config" ]; then

        echo 'graph_title Docker Container CPU usage'
        echo 'graph_args --base 1000 -l 0 '
        echo 'graph_scale no'
        echo 'graph_vlabel CPU usage'
        echo 'graph_category docker'
        for container in $($DockerCMD ps -aq --no-trunc)
        do
          cont=$(echo $container | cut -c -10)
          echo "docker_$cont.label docker_$cont"
          echo "docker_$cont.type DERIVE"
          echo "docker_$cont.min 0"
        done
        exit 0
fi

for container in $($DockerCMD ps -aq --no-trunc)
do
  cont=$(echo $container | cut -c -10)
  value=`awk '{sum+=$2} END {print sum}' /sys/fs/cgroup/cpuacct/system.slice/docker-$container.scope/cpuacct.stat`
  echo "docker_$cont.value $value"
done

