#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

docker_cpu - Plugin to measure memory usage of docker containers.

=head1 NOTES

Hopefully this works

=head1 AUTHOR

Contributed by Joe Seegmiller

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

. $MUNIN_LIBDIR/plugins/plugin.sh

DockerCMD=${docker:-$(which docker)}

if [ "$1" = "autoconf" ]; then
  if [ -x $DockerCMD ]; then
    echo yes
    exit 0
  else
    echo no '(docker not found)'
    exit 0
  fi
fi

if [ "$1" = "config" ]; then

        echo "multigraph docker_memory"
        echo "graph_title Docker Container Memory usage"
        echo 'graph_args --base 1024 -l 0 '
        echo 'graph_vlabel Bytes'
        echo 'graph_category docker'
        for container in $($DockerCMD ps -q --no-trunc)
        do
          cont=$(echo $container | cut -c -10)
          echo "$cont.label $cont"
          echo "$cont.type GAUGE"
        done
        for container in $($DockerCMD ps -q --no-trunc)
        do
          cont=$(echo $container | cut -c -10)
          echo "multigraph docker_memory.$cont"
          echo "graph_title Docker Container $cont Memory usage"
          echo 'graph_args --base 1024 -l 0 '
          echo 'graph_order rss cache swap'
          echo 'graph_vlabel Bytes'
          echo 'graph_category docker'
          echo "rss.label rss"
          echo "rss.type GAUGE"
          echo "rss.draw AREA"
          echo "rss.min 0"
          echo "cache.label cache"
          echo "cache.type GAUGE"
          echo "cache.draw STACK"
          echo "cache.min 0"
          echo "swap.label swap"
          echo "swap.type GAUGE"
          echo "swap.draw STACK"
          echo "swap.min 0"
        done
        exit 0
fi

for container in $($DockerCMD ps -q --no-trunc)
do
  cont=$(echo $container | cut -c -10)
  value=$(awk '/total_rss |total_cache |total_swap / {print$2}' /sys/fs/cgroup/memory/system.slice/docker-$container.scope/memory.stat | awk '{sum+=$1}END{print sum}')
  echo "$cont.value $value"
done



for container in $($DockerCMD ps -q --no-trunc)
do
  cont=$(echo $container | cut -c -10)
  echo "multigraph docker_memory.$cont"
  value=$(awk '/total_rss / {print$2}' /sys/fs/cgroup/memory/system.slice/docker-$container.scope/memory.stat)
  value2=$(awk '/total_cache / {print$2}' /sys/fs/cgroup/memory/system.slice/docker-$container.scope/memory.stat)
  value3=$(awk '/total_swap / {print$2}' /sys/fs/cgroup/memory/system.slice/docker-$container.scope/memory.stat)
  echo "rss.value $value"
  echo "cache.value $value2"
  echo "swap.value $value3"
done

